-- =========================================================
-- Pentaho Quartz Scheduler Database Creation - SQL Server
-- =========================================================

-- Create quartz database
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'quartz')
BEGIN
    CREATE DATABASE quartz;
    PRINT 'Database quartz created successfully';
END
ELSE
BEGIN
    PRINT 'Database quartz already exists';
END
GO

USE quartz;
GO

-- Create pentaho_user login if not exists
IF NOT EXISTS (SELECT name FROM sys.server_principals WHERE name = 'pentaho_user')
BEGIN
    CREATE LOGIN pentaho_user WITH PASSWORD = 'password', CHECK_POLICY = OFF;
    PRINT 'Login pentaho_user created successfully';
END
ELSE
BEGIN
    PRINT 'Login pentaho_user already exists';
END
GO

-- Create user in database if not exists
IF NOT EXISTS (SELECT name FROM sys.database_principals WHERE name = 'pentaho_user')
BEGIN
    CREATE USER pentaho_user FOR LOGIN pentaho_user;
    PRINT 'User pentaho_user created in quartz database';
END
ELSE
BEGIN
    PRINT 'User pentaho_user already exists in quartz database';
END
GO

-- Grant permissions
ALTER ROLE db_owner ADD MEMBER pentaho_user;
GO

-- Drop existing tables if they exist
IF OBJECT_ID('dbo.QRTZ6_FIRED_TRIGGERS', 'U') IS NOT NULL DROP TABLE dbo.QRTZ6_FIRED_TRIGGERS;
IF OBJECT_ID('dbo.QRTZ6_PAUSED_TRIGGER_GRPS', 'U') IS NOT NULL DROP TABLE dbo.QRTZ6_PAUSED_TRIGGER_GRPS;
IF OBJECT_ID('dbo.QRTZ6_SCHEDULER_STATE', 'U') IS NOT NULL DROP TABLE dbo.QRTZ6_SCHEDULER_STATE;
IF OBJECT_ID('dbo.QRTZ6_LOCKS', 'U') IS NOT NULL DROP TABLE dbo.QRTZ6_LOCKS;
IF OBJECT_ID('dbo.QRTZ6_SIMPLE_TRIGGERS', 'U') IS NOT NULL DROP TABLE dbo.QRTZ6_SIMPLE_TRIGGERS;
IF OBJECT_ID('dbo.QRTZ6_CRON_TRIGGERS', 'U') IS NOT NULL DROP TABLE dbo.QRTZ6_CRON_TRIGGERS;
IF OBJECT_ID('dbo.QRTZ6_SIMPROP_TRIGGERS', 'U') IS NOT NULL DROP TABLE dbo.QRTZ6_SIMPROP_TRIGGERS;
IF OBJECT_ID('dbo.QRTZ6_BLOB_TRIGGERS', 'U') IS NOT NULL DROP TABLE dbo.QRTZ6_BLOB_TRIGGERS;
IF OBJECT_ID('dbo.QRTZ6_TRIGGERS', 'U') IS NOT NULL DROP TABLE dbo.QRTZ6_TRIGGERS;
IF OBJECT_ID('dbo.QRTZ6_JOB_DETAILS', 'U') IS NOT NULL DROP TABLE dbo.QRTZ6_JOB_DETAILS;
IF OBJECT_ID('dbo.QRTZ6_CALENDARS', 'U') IS NOT NULL DROP TABLE dbo.QRTZ6_CALENDARS;
GO

-- Create Quartz tables
CREATE TABLE dbo.QRTZ6_JOB_DETAILS (
    SCHED_NAME VARCHAR(120) NOT NULL,
    JOB_NAME VARCHAR(200) NOT NULL,
    JOB_GROUP VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(250) NULL,
    JOB_CLASS_NAME VARCHAR(250) NOT NULL,
    IS_DURABLE VARCHAR(1) NOT NULL,
    IS_NONCONCURRENT VARCHAR(1) NOT NULL,
    IS_UPDATE_DATA VARCHAR(1) NOT NULL,
    REQUESTS_RECOVERY VARCHAR(1) NOT NULL,
    JOB_DATA VARBINARY(MAX) NULL,
    PRIMARY KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
);
GO

CREATE TABLE dbo.QRTZ6_TRIGGERS (
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    JOB_NAME VARCHAR(200) NOT NULL,
    JOB_GROUP VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(250) NULL,
    NEXT_FIRE_TIME BIGINT NULL,
    PREV_FIRE_TIME BIGINT NULL,
    PRIORITY INT NULL,
    TRIGGER_STATE VARCHAR(16) NOT NULL,
    TRIGGER_TYPE VARCHAR(8) NOT NULL,
    START_TIME BIGINT NOT NULL,
    END_TIME BIGINT NULL,
    CALENDAR_NAME VARCHAR(200) NULL,
    MISFIRE_INSTR SMALLINT NULL,
    JOB_DATA VARBINARY(MAX) NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
        REFERENCES dbo.QRTZ6_JOB_DETAILS(SCHED_NAME, JOB_NAME, JOB_GROUP)
);
GO

CREATE TABLE dbo.QRTZ6_SIMPLE_TRIGGERS (
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    REPEAT_COUNT BIGINT NOT NULL,
    REPEAT_INTERVAL BIGINT NOT NULL,
    TIMES_TRIGGERED BIGINT NOT NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES dbo.QRTZ6_TRIGGERS(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);
GO

CREATE TABLE dbo.QRTZ6_CRON_TRIGGERS (
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    CRON_EXPRESSION VARCHAR(200) NOT NULL,
    TIME_ZONE_ID VARCHAR(80),
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES dbo.QRTZ6_TRIGGERS(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);
GO

CREATE TABLE dbo.QRTZ6_SIMPROP_TRIGGERS (
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    STR_PROP_1 VARCHAR(512) NULL,
    STR_PROP_2 VARCHAR(512) NULL,
    STR_PROP_3 VARCHAR(512) NULL,
    INT_PROP_1 INT NULL,
    INT_PROP_2 INT NULL,
    LONG_PROP_1 BIGINT NULL,
    LONG_PROP_2 BIGINT NULL,
    DEC_PROP_1 NUMERIC(13,4) NULL,
    DEC_PROP_2 NUMERIC(13,4) NULL,
    BOOL_PROP_1 VARCHAR(1) NULL,
    BOOL_PROP_2 VARCHAR(1) NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES dbo.QRTZ6_TRIGGERS(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);
GO

CREATE TABLE dbo.QRTZ6_BLOB_TRIGGERS (
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    BLOB_DATA VARBINARY(MAX) NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES dbo.QRTZ6_TRIGGERS(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);
GO

CREATE TABLE dbo.QRTZ6_CALENDARS (
    SCHED_NAME VARCHAR(120) NOT NULL,
    CALENDAR_NAME VARCHAR(200) NOT NULL,
    CALENDAR VARBINARY(MAX) NOT NULL,
    PRIMARY KEY (SCHED_NAME, CALENDAR_NAME)
);
GO

CREATE TABLE dbo.QRTZ6_PAUSED_TRIGGER_GRPS (
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_GROUP)
);
GO

CREATE TABLE dbo.QRTZ6_FIRED_TRIGGERS (
    SCHED_NAME VARCHAR(120) NOT NULL,
    ENTRY_ID VARCHAR(95) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    INSTANCE_NAME VARCHAR(200) NOT NULL,
    FIRED_TIME BIGINT NOT NULL,
    SCHED_TIME BIGINT NOT NULL,
    PRIORITY INT NOT NULL,
    STATE VARCHAR(16) NOT NULL,
    JOB_NAME VARCHAR(200) NULL,
    JOB_GROUP VARCHAR(200) NULL,
    IS_NONCONCURRENT VARCHAR(1) NULL,
    REQUESTS_RECOVERY VARCHAR(1) NULL,
    PRIMARY KEY (SCHED_NAME, ENTRY_ID)
);
GO

CREATE TABLE dbo.QRTZ6_SCHEDULER_STATE (
    SCHED_NAME VARCHAR(120) NOT NULL,
    INSTANCE_NAME VARCHAR(200) NOT NULL,
    LAST_CHECKIN_TIME BIGINT NOT NULL,
    CHECKIN_INTERVAL BIGINT NOT NULL,
    PRIMARY KEY (SCHED_NAME, INSTANCE_NAME)
);
GO

CREATE TABLE dbo.QRTZ6_LOCKS (
    SCHED_NAME VARCHAR(120) NOT NULL,
    LOCK_NAME VARCHAR(40) NOT NULL,
    PRIMARY KEY (SCHED_NAME, LOCK_NAME)
);
GO

-- Insert initial lock records
INSERT INTO dbo.QRTZ6_LOCKS (SCHED_NAME, LOCK_NAME) VALUES ('PentahoQuartzScheduler', 'TRIGGER_ACCESS');
INSERT INTO dbo.QRTZ6_LOCKS (SCHED_NAME, LOCK_NAME) VALUES ('PentahoQuartzScheduler', 'JOB_ACCESS');
INSERT INTO dbo.QRTZ6_LOCKS (SCHED_NAME, LOCK_NAME) VALUES ('PentahoQuartzScheduler', 'CALENDAR_ACCESS');
INSERT INTO dbo.QRTZ6_LOCKS (SCHED_NAME, LOCK_NAME) VALUES ('PentahoQuartzScheduler', 'STATE_ACCESS');
INSERT INTO dbo.QRTZ6_LOCKS (SCHED_NAME, LOCK_NAME) VALUES ('PentahoQuartzScheduler', 'MISFIRE_ACCESS');
GO

PRINT 'Quartz database setup completed';
GO
